package com.mycompany.manajementugas;
import com.mycompany.manajementugas.TambahTugas;
import com.mycompany.manajementugas.EditTugas;
import com.mycompany.manajementugas.HapusTugas;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import net.proteanit.sql.DbUtils;

public class GUI_MT extends javax.swing.JFrame {
    private Statement St;
    private PreparedStatement Pst;
    private Connection Con;
    private ResultSet Rs;
    private String sql = "";
    
    public GUI_MT() {
        initComponents();
        KoneksiDatabase();
        tabelData.setDefaultEditor(Object.class, null);
        this.setLocationRelativeTo(null);
        
    }
    
    public void KoneksiDatabase(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tugas","root","12345");
            Pst = Con.prepareStatement("select Tenggat, Nama, Kategori, Status from tb_tugas");
            Rs = Pst.executeQuery();
            ResultSetMetaData rsmd = Rs.getMetaData();
            int n = rsmd.getColumnCount();
            DefaultTableModel model = (DefaultTableModel)tabelData.getModel();
            tabelData.removeColumn(tabelData.getColumnModel().getColumn(0));
            model.setRowCount(0);
            
            while(Rs.next()){
                Vector v = new Vector();
                for(int i=1; i<=n; i++){
                    v.add(Rs.getString("No"));
                    v.add(Rs.getString("Tenggat"));
                    v.add(Rs.getString("Nama"));
                    v.add(Rs.getString("Kategori"));
                    v.add(Rs.getString("Status"));
                }
                model.addRow(v);
            }
//            JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal" + e.getMessage());
        }
    }
    public void UpdateTable() {
        try{
            String sql = "select Tenggat, Nama, Kategori, Status from tb_tugas";
            Pst = Con.prepareStatement(sql);
            Rs = Pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(Rs));
            tabelData.removeColumn(tabelData.getColumnModel().getColumn(0));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hapusButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 119));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 5));

        hapusButton.setBackground(new java.awt.Color(255, 204, 51));
        hapusButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(51, 51, 51));
        hapusButton.setText("Hapus");
        hapusButton.setMaximumSize(new java.awt.Dimension(82, 26));
        hapusButton.setMinimumSize(new java.awt.Dimension(82, 26));
        hapusButton.setPreferredSize(new java.awt.Dimension(82, 26));
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahButton.setBackground(new java.awt.Color(255, 204, 51));
        tambahButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        tambahButton.setForeground(new java.awt.Color(51, 51, 51));
        tambahButton.setText("Tambah");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 204, 51));
        editButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        editButton.setForeground(new java.awt.Color(51, 51, 51));
        editButton.setText("Edit");
        editButton.setMaximumSize(new java.awt.Dimension(82, 26));
        editButton.setMinimumSize(new java.awt.Dimension(82, 26));
        editButton.setPreferredSize(new java.awt.Dimension(82, 26));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Progress:");

        jLabel1.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("MANAJEMEN TUGAS");

        exitButton.setBackground(new java.awt.Color(255, 204, 51));
        exitButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(51, 51, 51));
        exitButton.setText("Keluar");
        exitButton.setMaximumSize(new java.awt.Dimension(82, 26));
        exitButton.setMinimumSize(new java.awt.Dimension(82, 26));
        exitButton.setPreferredSize(new java.awt.Dimension(82, 26));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        tabelData.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Tenggat", "Nama", "Kategori", "Status"
            }
        ));
        tabelData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tabelData.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);

        refreshButton.setBackground(new java.awt.Color(255, 204, 51));
        refreshButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(51, 51, 51));
        refreshButton.setText("Refresh");
        refreshButton.setMaximumSize(new java.awt.Dimension(82, 26));
        refreshButton.setMinimumSize(new java.awt.Dimension(82, 26));
        refreshButton.setPreferredSize(new java.awt.Dimension(82, 26));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tambahButton)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98)
                                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahButton)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        TambahTugas tambah = new TambahTugas();
        tambah.setVisible(true);
        tambah.toFront();
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
//        TableModel model1 = tabelData.getModel();
//        int indexs[] = tabelData.getSelectedRows();
//        
//        Object[] row = new Object[4];
//        
//        HapusTugas hapus = new HapusTugas();
//        DefaultTableModel model2 = (DefaultTableModel)hapus.tabelData2.getModel();
//        
//        for(int i = 0; i < indexs.length; i++)
//        {
//            row[0] = model1.getValueAt(indexs[i], 0);
//            row[1] = model1.getValueAt(indexs[i], 1);
//            row[2] = model1.getValueAt(indexs[i], 2);
//            row[3] = model1.getValueAt(indexs[i], 3);
//            
//            model2.addRow(row);
//        }
        DefaultTableModel model = (DefaultTableModel) tabelData.getModel();
        int row = tabelData.getSelectedRow();
        String eve = tabelData.getModel().getValueAt(row, 0).toString();
        String delRow = "delete from tb_tugas where No="+eve;
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tugas","root","12345");
            St = Con.createStatement();
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus tugas ini?");
            if (confirm == 0) {
                if (!St.execute("delete from tb_tugas where No="+eve)){
                    JOptionPane.showMessageDialog(null, "Tugas Dihapus");
                }
                else {

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,  ex.getMessage());
        }
//        hapus.setVisible(true);
//        hapus.toFront();
    }//GEN-LAST:event_hapusButtonActionPerformed
    
    
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        EditTugas edit = new EditTugas();
//        int id = Integer.parseInt(tabelData.getValueAt(tabelData.getSelectedRow(), 0).toString());
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tugas","root","12345");
//            Pst = Con.prepareStatement("select * from tb_tugas where tb_tugas_id=" + id);
//            Rs = Pst.executeQuery();
//            while (Rs.next()){
//                edit.namaTugasField.setText(Rs.getString("Nama"));
//                edit.comboBox.setSelectedItem(Rs.getString("Kategori"));
//                edit.dateChooser.setDate(Rs.getDate("Tenggat"));
//            }
//        } catch(Exception e){
//            e.printStackTrace();
//        }
        edit.setVisible(true);
        edit.toFront();
    }//GEN-LAST:event_editButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
//        EditTugas edit = new EditTugas();
//        int id = Integer.parseInt(tabelData.getValueAt(tabelData.getSelectedRow(), 0).toString());
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tugas","root","12345");
//            Pst = Con.prepareStatement("select * from tb_tugas where tb_tugas_id=" + id);
//            Rs = Pst.executeQuery();
//            while (Rs.next()){
//                edit.namaTugasField.setText(Rs.getString("Nama"));
//                edit.comboBox.setSelectedItem(Rs.getString("Kategori"));
//                edit.dateChooser.setDate(Rs.getDate("Tenggat"));
//            }
//        } catch(Exception e){
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_tabelDataMouseClicked

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        try{
            String sql = "select * from tb_tugas";
            Pst = Con.prepareStatement(sql);
            Rs = Pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshButton;
    public javax.swing.JTable tabelData;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
